// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Butler is an autogenerated mock type for the Butler type
type Butler struct {
	mock.Mock
}

// SetupTestCalled provides a mock function with given fields:
func (_m *Butler) SetupTestCalled() {
	_m.Called()
}

// TearDownTestCalled provides a mock function with given fields:
func (_m *Butler) TearDownTestCalled() {
	_m.Called()
}
