// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Butler is an autogenerated mock type for the Butler type
type Butler struct {
	mock.Mock
}

// SetupTest provides a mock function with given fields:
func (_m *Butler) SetupTest() {
	_m.Called()
}

// TearDownTest provides a mock function with given fields:
func (_m *Butler) TearDownTest() {
	_m.Called()
}
